import React, { useMemo } from "react";
import DOMPurify from "dompurify";

/**
 * BlogContentRenderer safely renders rich-text HTML generated by TipTap or plain text.
 * It provides backward-compatibility for legacy plain-text posts and applies
 * polished medical typography styles.
 */
const BlogContentRenderer = ({ content, className = "" }) => {
  const sanitizedAndFormattedHtml = useMemo(() => {
    if (!content) return "";

    // Check if the content is rich HTML or legacy plain text
    const isHtml = /<[a-z][\s\S]*>/i.test(content);

    let rawHtml = content;
    if (!isHtml) {
      // Convert plain text into proper paragraphs
      rawHtml = content
        .split(/\n\s*\n/)
        .map((para) => `<p>${para.replace(/\n/g, "<br/>")}</p>`)
        .join("");
    }

    // Configure DOMPurify to allow links, images, headings, lists, formatting, etc.
    return DOMPurify.sanitize(rawHtml, {
      USE_PROFILES: { html: true },
      ADD_ATTR: ["target", "rel", "style"],
    });
  }, [content]);

  if (!sanitizedAndFormattedHtml) {
    return null;
  }

  return (
    <div
      className={`blog-rich-content ${className}`}
      dangerouslySetInnerHTML={{ __html: sanitizedAndFormattedHtml }}
    />
  );
};

export default BlogContentRenderer;
